[package]
name = "clifford"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A Rust library for Geometric Algebra (Clifford Algebra)"
keywords = ["geometric-algebra", "clifford-algebra", "mathematics", "simd", "linear-algebra"]
categories = ["mathematics", "science"]
repository = "https://github.com/DevonMorris/clifford"
readme = "README.md"

[lints.rust]
warnings = "deny"
missing_docs = "deny"

[lints.clippy]
all = { level = "deny", priority = -1 }
missing_docs_in_private_items = "deny"
uninlined_format_args = "allow"

[dependencies]

[dev-dependencies]
proptest = "1"
